FROM alpine:edge

MAINTAINER Konstantin Baierer <konstantin.baierer@gmail.com>

EXPOSE 8080
WORKDIR /ocr-fileformat
RUN apk add --no-cache openjdk8-jre php7 php7-json python py-lxml git make ca-certificates wget bash gcc libc-dev \
    && update-ca-certificates
COPY . /ocr-fileformat
RUN make install \
    && cp docker.config.php web/config.local.php \
    && sed -i '/^upload_max_filesize/ s/=.*$/= 100M/' /etc/php7/php.ini \
    && mv web /ocr-fileformat-web
VOLUME /data
WORKDIR /data
CMD php7 -S $(hostname -i):8080 -t /ocr-fileformat-web
