#!/bin/bash
INFILE="$1"
OUTFILE="$2"
#TODO
WIDTH=2000
HEIGHT=2000

is_temp=
if [[ "$2" = "-" ]];then
    is_temp=true
    OUTFILE="$(mktemp "/tmp/gcv2hocr_XXXXXXX.hocr")"
fi

./vendor/gcv2hocr/gcv2hocr "$INFILE" "$OUTFILE" "$WIDTH" "$HEIGHT"

if [[ "$is_temp" = true ]];then
    cat "$OUTFILE"
    rm "$OUTFILE"
fi
