#!/bin/bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENDORDIR="$(cd $SCRIPTDIR/../../vendor/; pwd)"
VENDORSCRIPT="$VENDORDIR/gcv2hocr/gcv2hocr"
INFILE="$1"
OUTFILE="$2"
#TODO
WIDTH=2000
HEIGHT=2000

if [[ "$1" = "-" ]]; then
    INFILE="$(mktemp)"
    cat >"$INFILE"
fi

if [[ "$2" = "-" ]]; then
    OUTFILE="$(mktemp)"
fi

"$VENDORSCRIPT" "$INFILE" "$OUTFILE" "$WIDTH" "$HEIGHT"

if [[ "$1" = "-" ]]; then
    rm "$INFILE"
fi

if [[ "$2" = "-" ]]; then
    cat "$OUTFILE"
    rm "$OUTFILE"
fi

rm preout1.txt preout2.txt
