#!/bin/bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENDORDIR="$(cd $SCRIPTDIR/../../vendor/; pwd)"
JAR="$VENDORDIR/JPageConverter/PageConverter.jar"
INFILE="$1"
OUTFILE="$2"

if [[ "$1" = "-" ]]; then
    INFILE="$(mktemp)"
    cat >"$INFILE"
fi

if [[ "$2" = "-" ]]; then
    OUTFILE="$(mktemp)"
fi

java -jar "$JAR" -neg-coords toZero -source-xml "$INFILE" -target-xml "$OUTFILE" -convert-to ALTO 2>&1

if [[ "$1" = "-" ]]; then
    rm "$INFILE"
fi

if [[ "$2" = "-" ]]; then
    cat "$OUTFILE"
    rm "$OUTFILE"
fi
