#!/bin/bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENDORDIR="$(cd $SCRIPTDIR/../../vendor/; pwd)"
INFILE="$1"
OUTFILE="$2"
ARGUMENTS=("${@:3}")

if [[ "$1" = "-" ]]; then
    INFILE="$(mktemp)"
    cat >"$INFILE"
fi

if [[ "$2" = "-" ]]; then
    OUTFILE="$(mktemp)"
fi

textract2page "${ARGUMENTS[@]:1}" -O "$OUTFILE" "$INFILE" "${ARGUMENTS[0]}"; retval="$?"

if [[ "$1" = "-" ]]; then
    rm "$INFILE"
fi

if (( retval > 0 ));then
    rm "$OUTFILE"
    exit $retval
fi

if [[ "$2" = "-" ]]; then
    cat "$OUTFILE"
    rm "$OUTFILE"
fi
