name: Continuous Integration

# Continuous integration test for ocr-fileformat.

on:
  # pull_request:
  # push:
  # schedule:
  #   - cron: 0 20 * * *
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install tesseract and other dependencies
      run: |
           sudo apt-get update
           sudo make -C example deps

    - name: Run make all
      run: |
           make all PREFIX=$HOME

    - name: Run tests
      run: |
           make -C example roundtrip diff
